FROM centos:7
MAINTAINER Matteo Cerutti <matteo.cerutti@hotmail.co.uk>

ADD MANIFEST.in /tmp/fluffy/
ADD README.md /tmp/fluffy/
ADD setup.py /tmp/fluffy/
ADD requirements.txt /tmp/fluffy/
ADD fluffy/ /tmp/fluffy/fluffy/
ADD contrib/uwsgi/ /app/
ADD etc /etc/fluffy/
RUN yum clean all && yum install -y epel-release && yum install -y python-pip iptables uwsgi uwsgi-plugin-python gcc-c++ python-devel nc && rm -rf /var/cache/yum/* && pushd /tmp/fluffy && pip install -r requirements.txt && python setup.py install && rm -rf /root/.cache && yum remove -y gcc-c++

VOLUME ["/var/lib/fluffy"]

ENTRYPOINT ["fluffyd"]
WORKDIR "/app"
CMD ["--log_level", "DEBUG"]
