---
version: 1
disable_existing_loggers: false
formatters:
  standard:
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
handlers:
  console:
    formatter: "standard"
    class: "logging.StreamHandler"
    stream: "ext://sys.stdout"
loggers:
  "fluffy":
    handlers:
      - "console"
    level: "INFO"
    propagate: true
  "werkzeug":
    handlers:
      - "console"
    level: "ERROR"
